// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJgqCuhRGTtnN5MnQcqNVVOmmdGVdjZQ',
    appId: '1:1065126010021:web:22b6e3b6320cd84cf9014c',
    messagingSenderId: '1065126010021',
    projectId: 'andrefirmansyah-f2129',
    authDomain: 'andrefirmansyah-f2129.firebaseapp.com',
    storageBucket: 'andrefirmansyah-f2129.firebasestorage.app',
    measurementId: 'G-ZJKEHG367D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7g2cjFvAz2ch5id4kAQ5Ntfda6Zv420',
    appId: '1:1065126010021:android:15e5ad93560eaaabf9014c',
    messagingSenderId: '1065126010021',
    projectId: 'andrefirmansyah-f2129',
    storageBucket: 'andrefirmansyah-f2129.firebasestorage.app',
  );
}
